/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Activity: () => import('#controllers/activity_controller'),
  auth: {
    Login: () => import('#controllers/auth/login_controller'),
    Logout: () => import('#controllers/auth/logout_controller'),
  },
  Dashboard: () => import('#controllers/dashboard_controller'),
  DoNotCall: () => import('#controllers/do_not_call_controller'),
  Documents: () => import('#controllers/documents_controller'),
  Go: () => import('#controllers/go_controller'),
  Healthcheck: () => import('#controllers/healthcheck_controller'),
  Maps: () => import('#controllers/maps_controller'),
  PublicMap: () => import('#controllers/public_map_controller'),
  Rurals: () => import('#controllers/rurals_controller'),
  Search: () => import('#controllers/search_controller'),
  Settings: () => import('#controllers/settings_controller'),
  Streets: () => import('#controllers/streets_controller'),
  WorkingNote: () => import('#controllers/working_note_controller'),
}
