/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class ActivitySchema extends BaseModel {
  static $columns = ['id', 'inDate', 'mapId', 'notes', 'outDate', 'publisher', 'status'] as const
  $columns = ActivitySchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime()
  declare inDate: DateTime | null
  @column()
  declare mapId: string
  @column()
  declare notes: string | null
  @column.dateTime()
  declare outDate: DateTime
  @column()
  declare publisher: string
  @column()
  declare status: string
}

export class CongregationSchema extends BaseModel {
  static $columns = ['broughtBackConfirmationMessage', 'name', 'number', 'password', 'securityToken', 'shareMessage'] as const
  $columns = CongregationSchema.$columns
  @column()
  declare broughtBackConfirmationMessage: string
  @column()
  declare name: string
  @column({ isPrimary: true })
  declare number: string
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare securityToken: string | null
  @column()
  declare shareMessage: string
}

export class DoNotCallSchema extends BaseModel {
  static $columns = ['address', 'id', 'lastCalled', 'mapId'] as const
  $columns = DoNotCallSchema.$columns
  @column()
  declare address: string
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime()
  declare lastCalled: DateTime
  @column()
  declare mapId: string
}

export class MapSchema extends BaseModel {
  static $columns = ['code', 'congregationNumber', 'id', 'imageName', 'messageFromServant', 'messageToServant', 'name', 'typeId'] as const
  $columns = MapSchema.$columns
  @column()
  declare code: string
  @column()
  declare congregationNumber: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare imageName: string
  @column()
  declare messageFromServant: string
  @column()
  declare messageToServant: string
  @column()
  declare name: string
  @column()
  declare typeId: string
}

export class MapTypeSchema extends BaseModel {
  static $columns = ['congregationNumber', 'id', 'name'] as const
  $columns = MapTypeSchema.$columns
  @column()
  declare congregationNumber: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
}

export class RateLimitSchema extends BaseModel {
  static $columns = ['expire', 'key', 'points'] as const
  $columns = RateLimitSchema.$columns
  @column()
  declare expire: bigint | number | null
  @column({ isPrimary: true })
  declare key: string
  @column()
  declare points: number
}

export class RuralSchema extends BaseModel {
  static $columns = ['description', 'id', 'isComplete', 'latitude', 'longitude', 'mapId', 'what3Words'] as const
  $columns = RuralSchema.$columns
  @column()
  declare description: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isComplete: boolean
  @column()
  declare latitude: number
  @column()
  declare longitude: number
  @column()
  declare mapId: string
  @column()
  declare what3Words: string
}

export class StreetSchema extends BaseModel {
  static $columns = ['id', 'isComplete', 'mapId', 'name'] as const
  $columns = StreetSchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isComplete: boolean
  @column()
  declare mapId: string
  @column()
  declare name: string
}

export class StreetCategorySchema extends BaseModel {
  static $columns = ['congregationNumber', 'id', 'name'] as const
  $columns = StreetCategorySchema.$columns
  @column()
  declare congregationNumber: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
}

export class WhatsNewSchema extends BaseModel {
  static $columns = ['addedAt', 'content', 'id'] as const
  $columns = WhatsNewSchema.$columns
  @column.dateTime()
  declare addedAt: DateTime
  @column()
  declare content: string
  @column({ isPrimary: true })
  declare id: string
}

export class WorkingNoteSchema extends BaseModel {
  static $columns = ['colour', 'congregationNumber', 'content', 'id', 'lastUpdated'] as const
  $columns = WorkingNoteSchema.$columns
  @column()
  declare colour: string
  @column()
  declare congregationNumber: string
  @column()
  declare content: string
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime()
  declare lastUpdated: DateTime
}

export class StreetToStreetCategorySchema extends BaseModel {
  static $columns = ['a', 'b'] as const
  $columns = StreetToStreetCategorySchema.$columns
  @column()
  declare a: string
  @column()
  declare b: string
}
