/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="./manifest.d.ts" />
import type { InferData, InferVariants } from '@adonisjs/core/types/transformers'
import type { InferSharedProps } from '@adonisjs/inertia/types'
import type CongregationTransformer from '#transformers/congregation_transformer'
import type InertiaMiddleware from '#middleware/inertia_middleware'

export namespace Data {
  export type Congregation = InferData<CongregationTransformer>
  export namespace Congregation {
    export type Variants = InferVariants<CongregationTransformer>
  }
  export type SharedProps = InferSharedProps<InertiaMiddleware>
}
